---
- name: Verify proper varibles
  assert:
    that:
      - radiusSrvs
    quiet: true
- name: Create apic connection profile
  set_fact:
    login: &aci_login
      host: "{{ ansible_host }}"
      use_proxy: "{{ apic_proxy | default('no') }}"
      validate_certs: "{{ apic_validate_certs | default('no') }}"
      use_ssl: "{{ apic_use_ssl | default('yes') }}"
      private_key: "{{ playbook_dir }}/{{ varprompt_private_key }}"
      #certificate_name: admin
    intentMap:
      add: present
      remove: absent

- name: |
    "{{ intent }} Radius Server
    Admin->Authentication->RADIUS"
  cisco.aci.aci_rest:
    <<: *aci_login
    path: "/api/node/mo/uni/userext/radiusext/radiusprovider-{{ item | string }}.json"
    method: post
    content:
      aaaRadiusProvider:
        attributes:
          name: "{{ item | string }}"
          authProtocol: "{{ radiusAuthProtocol }}"
          key: "{{ radiusPwd }}"
          status: "{{ 'deleted' if intent == 'remove' }}"
        children:
        - aaaRsSecProvToEpg:
            attributes:
              tDn: "uni/tn-mgmt/mgmtp-default/oob-{{ oobEpg }}"
            children: []
  loop: "{{ radiusSrvs }}"
  loop_control:
    label: "{{ intent }} radius srv {{ item | string }}"
- name: |
    "{{ intent }} default auth to radius
    Admin->Authentication"
  cisco.aci.aci_rest:
    <<: *aci_login
    path: "/api/node/mo/uni/userext/authrealm/defaultauth.json"
    method: post
    content:
      aaaDefaultAuth:
        attributes:
          realm: radius
- name: |
    "confirm fallback domain is set to local auth"
  cisco.aci.aci_rest:
    <<: *aci_login
    path: "/api/node/mo/uni/userext/logindomain-fallback/domainauth.json"
    method: post
    content:
      aaaDomainAuth:
        attributes:
          realm: local
  when: intent == "add"
- name: |
    "default auth to local
    Admin->Authentication"
  cisco.aci.aci_rest:
    <<: *aci_login
    path: "/api/node/mo/uni/userext/authrealm/defaultauth.json"
    method: post
    content:
      aaaDefaultAuth:
        attributes:
          realm: local
  when: intent == "remove"

