---
vlanPools:
- &prodVlanPool
  name: prod
  alloc: static
  vlans:
  - blockStart: 1000
    blockEnd: 1099
- &devVlanPool
    name: dev
    alloc: static
    vlans:
    - blockStart: 50
      blockEnd: 100
- &vmmVlanPool
  name: vmm
  alloc: dynamic
  vlans:
  - blockStart: 1500
    blockEnd: 1800
- &legacyPool
  name: legacy
  alloc: static
  vlans:
  - blockStart: 500
    blockEnd: 500
  - blockStart: 501
    blockEnd: 501
  - blockStart: 502
    blockEnd: 502
- &l3OutPool 
  name: l3-out
  alloc: static
  vlans:
  - blockStart: 4000
    blockEnd: 4050
domains:
- &prodDomain
  name: prod
  domain_type: phys
  vlan:
    *prodVlanPool
- &devDomain
    name: dev
    domain_type: phys
    vlan:
      *devVlanPool
- &vmwareDomain
  name: vmware-aci
  domain_type: vmm
  vm_provider: vmware
  vlan:
    *vmmVlanPool
- &l3OutDomain
  name: l3-out
  domain_type: l3dom
  vlan:
    *l3OutPool
- &legacyDomain
  name: legacy
  domain_type: phys
  vlan:
    *legacyPool
aeps:
- name: phy
  domains:
  - *prodDomain
  - *devDomain
- name: vmware
  domains:
  - *vmwareDomain
- name: l3out
  domains:
  - *l3OutDomain
- name: legacy
  domains:
  - *legacyDomain
    




